<form id="formAddAdmin" style="margin-top: 50px">
    <div class="container-model-100p" style="text-align: center">
        <h2>Register Manager</h2>
    </div>
  <div class="container-model-50p fleft">
    <label><b>Manager Name :</b><font style="color: red"> *</font></label><div id="user_first_name_is_true"></div>
    <input type="text" class="input100p"
	    name="admin[admin_name]" 
	    value="" 
	    required
	>

    <label><b>Login Name</b><font style="color: red"> *</font></label><div id="user_last_name_is_true"></div>
    <input type="text" class="input100p"
	    name="admin[admin_login_name]" value=""
	    required
	>
  </div>
  <div class="container-model-50p fleft">
    <label><b>Password :</b><font style="color: red"> *</font></label><div id="user_email_is_true"></div>
    <input type="password"  class="input100p"
	    name="admin[admin_pass]" 
	    id="user_email" value=""
	    required
    >

    <label><b>Chosse group :</b><font style="color: red"> *</font></label><div id="user_login_pass_is_true"></div>
    <select name="admin[admin_group_permisstion]" class="input100p">
        <option value=""></option>
        <?php foreach ($this->aryGroup as $group) { ?>
            <option value="<?php echo $group['id'] ?>"><?php echo $group['group_permission_name'] ?></option>
        <?php } ?>
    </select>
  </div>
  <div class="container-model-100p" style="background-color:#f1f1f1; text-align: center">
      <button class="input100p" type="submit" onclick="Admin.saveAdmin('')">Register</button>
  </div>
</form>
