<div class="row" style="margin-top: 30px">
    <div class="col-lg-4 card-header" style="overflow-y: auto;background-color: lightblue;">
        <h3>List group permission</h3>
    </div> 
    <div class="col-lg-3 card-header" style="overflow-y: auto;background-color: lightblue;">
        <h3>List member</h3>
    </div>  
    <div class="col-lg-5 card-header" style="overflow-y: auto;background-color: lightblue;">
        <h3>Group detail</h3>
    </div>  
    <div class="col-lg-4 card" style="overflow-y: auto; height: 620px">
        <div class="list-group list-group-flush small" style="margin-top: 10px" id="listPermissionGroup">
            <?php foreach ($this->aryGroups as $group) { ?>
            <a class="list-group-item list-group-item-action" href="#" onclick="Admin.loadGroupDetail(<?php echo $group['id']; ?>)">
                    <div class="media">
                        <div class="media-body" style="width: 400px; white-space: nowrap;text-overflow: ellipsis;overflow: hidden;">
                          <strong style="font-size: 21px;"><?php echo $group['group_permission_name']; ?></strong>
                          <div class="text-muted" style="font-size: 15px">Created by : <font style="color: red"><?php 
                            foreach ($this->aryAdmins as $admin) {
                                if ($admin['id'] == $group['group_permission_creater']) {
                                    echo $admin['admin_name'];
                                }
                            }
                            ?></font></div>
                      </div>
                    </div>
                </a>
            <?php } ?>
        </div>
    </div>
    <div class="col-lg-3 card" id="box_group_detail_list_member" style="overflow-y: auto; height: 620px"></div>  
    <div class="col-lg-5 card" id="box_group_detail" style="overflow-y: auto; height: 620px"></div>  
</div>

