<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>SB Admin - Start Bootstrap Template</title>
  <!-- Bootstrap core CSS-->
  <link href="<?php echo $this->baseUrl('admin/vendor/bootstrap/css/bootstrap.min.css');?>" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <link href="<?php echo $this->baseUrl('admin/vendor/font-awesome/css/font-awesome.min.css') ?>" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href="<?php echo $this->baseUrl('admin/css/sb-admin.css') ?>" rel="stylesheet">
  <script type="text/javascript">
    	var ROOT_URL = "<?php echo $this->baseUrl(); ?>" + "/index.php/Admin";
  </script>
</head>

<body class="bg-dark">
  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Login</div>
      <div class="card-body">
          <form id="loginAdmin">
          <div class="form-group">
            <label for="exampleInputEmail1">Login Name</label>
            <input class="form-control" id="exampleInputEmail1" name="admin[admin_login_name]" type="text" placeholder="Enter Login Name" required>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Login Password</label>
            <input class="form-control" id="exampleInputPassword1" name="admin[admin_pass]" type="password" placeholder="Password" required>
          </div>
          <div class="form-group">
            <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox"> Remember Password</label>
            </div>
          </div>
              <button type="submit" class="btn btn-primary btn-block" onclick="Admin.login()">Login</button>
        </form>
      </div>
    </div>
  </div>
  <!-- Bootstrap core JavaScript-->
  <script src="<?php echo $this->baseUrl('admin/vendor/jquery/jquery.min.js')?>"></script>
<script src="http://malsup.github.com/jquery.form.js"></script> 
  <script src="<?php echo $this->baseUrl('admin/vendor/bootstrap/js/bootstrap.bundle.min.js')?>"></script>
  <!-- Core plugin JavaScript-->
  <script src="<?php echo $this->baseUrl('admin/vendor/jquery-easing/jquery.easing.min.js')?>"></script>
  <script src="<?php echo $this->baseUrl('admin/js.js')?>"></script>
        <!--jquery form-->

        <script>
            // Get the modal
            var modal = document.getElementById('box-popup');

            // When the user clicks anywhere outside of the modal, close it
            window.onclick = function(event) {
                if (event.target == modal) {
                    Default.closePopup();
                }
            }
        </script>
</body>

</html>
