<ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard" onclick="Default.setSelectedItemMenuLeft(this)">
      <a class="nav-link" href="index.html">
        <i class="fa fa-fw fa-dashboard"></i>
        <span class="nav-link-text">Home</span>
      </a>
    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts" onclick="Default.setSelectedItemMenuLeft(this)">
      <a class="nav-link" href="charts.html">
        <i class="fa fa-fw fa-area-chart"></i>
        <span class="nav-link-text">Charts</span>
      </a>
    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables" onclick="Default.setSelectedItemMenuLeft(this)">
      <a class="nav-link" href="tables.html">
        <i class="fa fa-fw fa-table"></i>
        <span class="nav-link-text">Videos</span>
      </a>
    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components" onclick="Default.setSelectedItemMenuLeft(this)">
      <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
        <i class="fa fa-fw fa-wrench"></i>
        <span class="nav-link-text">List Video</span>
      </a>
      <ul class="sidenav-second-level collapse" id="collapseComponents">
        <li>
          <a href="navbar.html">Navbar</a>
        </li>
        <li>
          <a href="cards.html">Cards</a>
        </li>
      </ul>
    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Example Pages" onclick="Default.setSelectedItemMenuLeft(this)">
      <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseExamplePages" data-parent="#exampleAccordion">
        <i class="fa fa-fw fa-file"></i>
        <span class="nav-link-text">Permission</span>
      </a>
      <ul class="sidenav-second-level collapse" id="collapseExamplePages">
        <li>
            <a onclick="Admin.showFormAddGroupPermission()">Create group permission</a>
        </li>
        <li>
            <a onclick="Admin.loadListGroupPermission()">Show list permission</a>
        </li>
      </ul>
    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu Levels" onclick="Default.setSelectedItemMenuLeft(this);Admin.loadListMember()">
        <a class="nav-link nav-link-collapse collapsed">
        <i class="fa fa-fw fa-sitemap"></i>
        <span class="nav-link-text">List Member</span>
      </a>
    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link" onclick="Default.setSelectedItemMenuLeft(this)">
      <a class="nav-link" href="#">
        <i class="fa fa-fw fa-link"></i>
        <span class="nav-link-text">Link</span>
      </a>
    </li>
</ul>