<ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard" onclick="Default.setSelectedItemMenuLeft(this)">
      <a class="nav-link" href="index.html">
        <i class="fa fa-fw fa-dashboard"></i>
        <span class="nav-link-text">Home</span>
      </a>
    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts" onclick="Default.setSelectedItemMenuLeft(this)">
      <a class="nav-link" href="charts.html">
        <i class="fa fa-fw fa-area-chart"></i>
        <span class="nav-link-text">Charts</span>
      </a>
    </li>
    <?php foreach ($_SESSION['Admin']['permission'] as $permission) { if ($permission == "")  continue; 
        echo $this->configPermission[$permission];
    } ?>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link" onclick="Default.setSelectedItemMenuLeft(this)">
      <a class="nav-link" href="#">
        <i class="fa fa-fw fa-link"></i>
        <span class="nav-link-text">Link</span>
      </a>
    </li>
</ul>