<div class="row" style="margin-top: 30px">
    <div class="col-lg-4 card-header" style="overflow-y: auto">
        <h3>Users</h3>
    </div>  
    <div class="col-lg-8 card-header" style="overflow-y: auto">
        <h3>List Video</h3>
    </div>  
    <div class="col-lg-4 card" style="overflow-y: auto; height: 620px">
        <div class="list-group list-group-flush small" style="margin-top: 10px;" id="listMembers">
            <?php foreach ($this->aryUser as $user) { ?>
            <a class="list-group-item list-group-item-action"  href="#" onclick="Admin.loadListVideoByUser('<?php echo $user['user_code'];?>')">
                    <div class="media">
                        <div class="media-body" style="width: 400px; white-space: nowrap;text-overflow: ellipsis;overflow: hidden;">
                          <strong style="font-size: 21px;"><?php echo $user['user_full_name']; ?></strong>
                          <div class="text-muted" style="font-size: 15px">Created on : <font style="color: red"><?php
                            echo $user['created'];
                          ?></font></div>
                      </div>
                    </div>
                </a>
            <?php } ?>
        </div>
    </div>
    <div class="col-lg-8 card" id="box_list_by_user" style="overflow-y: auto; height: 620px"></div>  
</div>

