<div class="overlay"></div>
<div class="" id="box_search_video" style="margin-top:72px; text-align: center">
    <input type="text" onkeyup="Default.searchVideo(this)" class="form-control-lg w25p" placeholder="Search for...">
</div>
<div class="" id="box_search_video_list_value" style="text-align: center; overflow-x: auto; margin: 5px 5% 0px 5%; box-sizing: border-box;">
</div>
<div style="text-align: center; overflow-x: auto; margin: 20px 5% 20px 5%; box-sizing: border-box;height:70px;">
    <div class="w100p">
        <!-- START #fh5co-logo -->
        <h1 class="pull-right mar-right-2p" style="font-size: 20px;font-weight: bold;"><a class="hover opacity05" href="#" onclick="Default.filterListVideo('video_view')">MOST VIEW</a></h1>
        <h1 class="pull-right mar-right-2p" style="font-size: 20px;font-weight: bold;"><a class="hover opacity05" href="#" onclick="Default.filterListVideo('created')">NEWEST</a></h1>
        <h1 class="pull-right mar-right-2p" style="font-size: 20px;font-weight: bold;"><a class="hover opacity05" href="#" onclick="Default.filterListVideo('video_view')">LIST MOST VIEW</a></h1>
    </div>
</div>
<div class="container-fluid" id="box_content_home">
    <?php
    $listVideoType = $this->listAryVideoType;
    foreach ($listVideoType as $videoType) : 
        ?>
        <fieldset style="border: none">
            <legend style=" font-weight: bold; color: black"><?php echo $videoType['video_type_title'] ?></legend>
            <div id="listVideo<?php echo $videoType['id']; ?>">
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                      <li class="page-item">
                        <?php if($this->{'hasFirst'.$videoType['id']}) : ?>
                            <a class="page-link" href="#" aria-label="Previous1" onclick="User.loadPagination('Video','loadlistvideobyhome','<?php echo $this->{'firstPage'.$videoType['id']} ?>','listVideo<?php echo $videoType['id'] ?>',<?php echo $videoType['id'] ?>)">
                                <span aria-hidden="true"> << </span>
                                <span class="sr-only">Previous1</span>
                            </a>
                        <?php else : ?>
                        <?php endif; ?>
                      </li>
                      <li class="page-item">
                        <?php if ($this->{'hasPrev'.$videoType['id']}) : ?>
                            <!-- <a href="">First</a> -->
                            <a class="page-link" href="#" aria-label="Previous2" onclick="User.loadPagination('Video','loadlistvideobyhome','<?php echo $this->{'previousPage'.$videoType['id']} ?>','listVideo<?php echo $videoType['id'] ?>',<?php echo $videoType['id'] ?>)">
                            <span aria-hidden="true"> < </span>
                            <span class="sr-only">Previous2</span>
                        </a>
                        <?php else : ?>
                        <?php endif; ?> 
                      </li>
                      <?php if ($this->{'countPages'.$videoType['id']} != $this->{'currentPage'.$videoType['id']}) : ?>
                      <li class="page-item"><a class="page-link" href="#"><?php echo "".$this->{'currentPage'.$videoType['id']}."/".$this->{'countPages'.$videoType['id']}; ?></a></li>
                      <?php endif; ?>
                      <li class="page-item">
                          <?php if ($this->{'hasNext'.$videoType['id']}) : ?>
                            <a class="page-link" href="#" aria-label="Next1" href="#" onclick="User.loadPagination('Video','loadlistvideobyhome','<?php echo $this->{'nextPage'.$videoType['id']} ?>','listVideo<?php echo $videoType['id'] ?>',<?php echo $videoType['id'] ?>)"> 
                                <span aria-hidden="true"> > </span>
                                <span class="sr-only">Next1</span>
                            </a>
                          <?php else : ?>
                          <?php endif; ?>
                      </li>
                      <li class="page-item">
                          <?php if($this->{'hasEnd'.$videoType['id']}) : ?>
                            <a class="page-link" href="#" aria-label="Next" onclick="User.loadPagination('Video','loadlistvideobyhome','<?php echo $this->{'endPage'.$videoType['id']} ?>','listVideo<?php echo $videoType['id'] ?>',<?php echo $videoType['id'] ?>)">
                                <span aria-hidden="true"> >> </span>
                                <span class="sr-only">Next</span>
                            </a>
                      </li>
                          <?php else : ?>
                          <?php endif; ?> 
                    </ul>
                </nav>
                <?php 
                foreach ($this->{"listAryVideo".$videoType['id']} as $video) :
                    if ($video['video_video_type_code'] == $videoType['id']) : ?>
                        <div class="col-lg-3 col-md-6 col-sm-6 animate-box">
                            <a class="fh5co-card" href="<?php echo $this->baseUrl("Video/view/id/".$video['id']); ?>">
                                <img class="itemAliasVideo" src="<?php echo $this->baseUrl($video['video_url_image_alias']); ?>" alt="Free HTML5 Bootstrap template" class="img-responsive">
                                <div class="fh5co-card-body">
                                    <h3 style="color: #004085; word-wrap:  break-word;"><?php echo $video['video_title']; ?></h3>
                                    <p style="word-wrap:  break-word;"><?php echo (strlen($video['video_description']) > 100)? substr($video['video_description'],0,100)."..." : $video['video_description'];?></p>
                                </div>
                            </a>
                        </div>
                    <?php endif;
                endforeach; ?>
            </div>
        </fieldset>
    <?php endforeach;
    ?>

</div>	
