<nav aria-label="Page navigation example" style="width: 100%">
        <ul class="pagination">
          <li class="page-item">
            <?php if($this->hasFirst) : ?>
                <a class="page-link" href="#" aria-label="Previous1" onclick="User.loadPagination('Index','listvideobymenu','<?php echo $this->firstPage ?>','box_content_home')">
                    <span aria-hidden="true"> << </span>
                    <span class="sr-only">Previous1</span>
                </a>
            <?php else : ?>
            <?php endif; ?>
          </li>
          <li class="page-item">
            <?php if ($this->hasPrev) : ?>
                <!-- <a href="">First</a> -->
                <a class="page-link" href="#" aria-label="Previous2" onclick="User.loadPagination('Index','listvideobymenu','<?php echo $this->previousPage ?>','box_content_home')">
                <span aria-hidden="true"> < </span>
                <span class="sr-only">Previous2</span>
            </a>
        <?php else : ?>
        <?php endif; ?>
      </li>
          <li class="page-item"><a class="page-link" href="#"><?php echo "".$this->currentPage."/".$this->countPages; ?></a></li>
      <li class="page-item">
          <?php if ($this->hasNext) : ?>
            <a class="page-link" href="#" aria-label="Next1" href="#" onclick="User.loadPagination('Index','listvideobymenu','<?php echo $this->nextPage ?>','box_content_home')"> 
                <span aria-hidden="true"> > </span>
                <span class="sr-only">Next1</span>
            </a>
          <?php else : ?>
          <?php endif; ?>
      </li>
      <li class="page-item">
          <?php if($this->hasEnd) : ?>
            <a class="page-link" href="#" aria-label="Next" onclick="User.loadPagination('Index','listvideobymenu','<?php echo $this->endPage ?>','box_content_home')"> 
                <span aria-hidden="true"> >> </span>
                <span class="sr-only">Next</span>
            </a>
      </li>
          <?php else : ?>
          <?php endif; ?> 
    </ul>
</nav>               
<?php foreach ($this->aryListVideo as $aryVideo) { ?>
    <div class="col-lg-3 col-md-6 col-sm-6" style="height: 300px; margin-top: 10px">
        <a class="fh5co-card" href="<?php echo $this->baseUrl("Video/view/id/".$aryVideo['id']); ?>">
            <img class="itemAliasVideo" src="<?php echo $this->baseUrl($aryVideo['video_url_image_alias']);?>" alt="Free HTML5 Bootstrap template" class="img-responsive">
            <div class="fh5co-card-body">
                <h3 style="color: #004085; word-wrap:  break-word;"><?php echo (strlen($aryVideo['video_title']) > 50)? substr($aryVideo['video_title'],0,50)."..." : $aryVideo['video_title'];?></h3>
                <p style="word-wrap:  break-word;"><?php echo (strlen($aryVideo['video_description']) > 100)? substr($aryVideo['video_description'],0,100)."..." : $aryVideo['video_description'];?></p>
            </div>
        </a>
    </div>
<?php } ?>
<!-- End Right Column -->