<form id="formAddList" class="modal-content-register animate" enctype="multipart/form-data">
    <div class="container-model-100p fleft" style="background-color:#f1f1f1">
        <label style="font-size: 25px"><b>List Title :</b><font style="color: red"> *</font></label>
      <input type="text" class="input100p"
              name="list_video[video_group_group_code]" 
              id="user_first_name" value="<?php echo (isset($this->aryListVideo['video_group_group_code'])) ? $this->aryListVideo['video_group_group_code'] :"";?>" 
              required
          >

      <label style="font-size: 25px"><b>Is public:</b><font style="color: red"> *</font></label>
      <input type="checkbox"
             name="list_video[video_group_status]" value="1" <?php echo ($this->aryListVideo['video_group_status'] != 0) ? "checked" : "";?>
              id="user_last_name" 
          >
      <input type="hidden" value="<?php echo (isset($this->aryListVideo['video_group_video_code'])) ? $this->aryListVideo['video_group_video_code'] :"";?>" name="list_video[video_group_video_code]" id="video_in_list" >
      <input type="hidden" value="<?php echo (isset($this->aryListVideo['id'])) ? $this->aryListVideo['id'] :"";?>" name="id_list_video"  id="id_list_video">
    </div>
    <div class="container-model-100p fleft" id="box_video_in_list" style="overflow-x: auto; box-sizing: border-box;background-color:#f1f1f1;">
        <?php 
        if ($this->aryVideosInlist !== []) { ?>
            <div style="width: <?php echo ((250*count($this->aryVideosInlist)) > 1255) ? 250*count($this->aryVideosInlist) : "1250"?>px; height: 320px; background-color: white;">
        <?php     
            foreach ($this->aryVideosInlist as $key => $video) :
        ?>
                <div class="fadeInUp animated w3-white w3-text-grey w3-card-4" id="video_in_list_<?php echo $video['id'] ?>" style="width: 235px; float: left;margin-right: 10px;">
                <div style="width: 90%;"><a href="#" class="" onclick="VideoList.removeVideoTolist(<?php echo $video['id'] ?>,'video_in_list_<?php echo $video['id'] ?>')" style=" font-size: 24px"><i class="fa fa-remove w3-margin-right w3-large w3-text-red"></i></a></div>
                <div style="height: 285px">
                    <a class="fh5co-card" href="<?php echo $this->baseUrl("Video/view/id/".$video['id']); ?>">
                        <img class="itemAliasVideo" src="<?php echo $this->baseUrl($video['video_url_image_alias']); ?>" alt="Free HTML5 Bootstrap template">
                        <div class="fh5co-card-body">
                            <h3 style="color: #004085; word-wrap:  break-word;"><?php echo (strlen($video['video_title']) > 100)? substr($video['video_title'],0,100)."..." : $video['video_title']; ?></h3>
                        </div>
                    </a>
                </div>
            </div>
        <?php 
        endforeach;?>
            </div>    
        <?php 
        } else { ?>
            <div style="width:1250px; height: 320px; background-color: white; display: none">
            </div>
        <?php     
        }
        ?>
    </div>
    <div class="container-model-100p fleft" id="box_video_add_list" style="overflow-x: auto; box-sizing: border-box;background-color:#f1f1f1;">
        <?php 
        if ($this->aryListVideoNotInList !== []) { ?>
            <div style="width: <?php echo ((250*count($this->aryListVideoNotInList)) > 1255) ? 250*count($this->aryListVideoNotInList) : "1250"?>px; height: 320px; background-color: white;">
        <?php     
            foreach ($this->aryListVideoNotInList as $key => $video) :
        ?>
                <div class="fadeInUp animated w3-white w3-text-grey w3-card-4" id="video_not_in_list_<?php echo $video['id'] ?>" style="width: 235px; float: left;margin-right: 10px;">
                <div style="width: 90%;"><a href="#" class="" onclick="VideoList.addVideoTolist(<?php echo $video['id'] ?>,'video_not_in_list_<?php echo $video['id'] ?>')" style=" font-size: 24px"><i class="fa fa-plus w3-margin-right w3-large w3-text-red"></i></a></div>
                <div style="height: 285px">
                    <a class="fh5co-card" href="<?php echo $this->baseUrl("Video/view/id/".$video['id']); ?>">
                        <img class="itemAliasVideo" src="<?php echo $this->baseUrl($video['video_url_image_alias']); ?>" alt="Free HTML5 Bootstrap template">
                        <div class="fh5co-card-body">
                            <h3 style="color: #004085"><?php echo (strlen($video['video_title']) > 100)? substr($video['video_title'],0,100)."..." : $video['video_title']; ?></h3>
                        </div>
                    </a>
                </div>
            </div>
        <?php 
        endforeach;?>
            </div>    
        <?php 
        } else { ?>
            <div style="width:1250px; height: 320px; background-color: white; display: none">
            </div>
        <?php     
        }
        ?>
    </div>
    <div class="container-model-100p fleft" style="background-color:#f1f1f1; height: 120px;text-align: center">
        <button type="submit" onclick="VideoList.saveListVideo(<?php echo (isset($this->aryListVideo['id'])) ? $this->aryListVideo['id'] : "";?>)">Save</button>
        <?php if (isset($this->aryListVideo['id']) && $this->aryListVideo['id'] !== "") : ?>
        <button type="button" onclick="VideoList.deleteList(<?php echo (isset($this->aryListVideo['id'])) ? $this->aryListVideo['id'] : "";?>)" style="background-color: red; margin-left: 5px;">Delete</button>
        <?php endif; ?>
        <button type="button" onclick="Default.closePopup('formAddList')" style="background-color: red; margin-left: 5px;">Cancel</button>
    </div>
  <div id="list_message_error">
    
  </div>
</form>
