<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Valet &mdash; Free HTML5 Bootstrap Template by FREEHTML5.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	<meta name="author" content="FREEHTML5.CO" />

  	<!-- 
	//////////////////////////////////////////////////////

	FREE HTML5 TEMPLATE 
	DESIGNED & DEVELOPED by FREEHTML5.CO
	
	Website: 		http://freehtml5.co/
	Email: 			info@freehtml5.co
	Twitter: 		http://twitter.com/fh5co
	Facebook: 	https://www.facebook.com/fh5co

	//////////////////////////////////////////////////////
	 -->

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

  	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
  	<link rel="shortcut icon" href="favicon.ico">
        <link href="<?php echo $this->baseUrl('client/lib-css/bootstrap.css'); ?>" rel="stylesheet" type="text/css"/>
  	<!-- Google Webfont -->
	<!-- <link href='http://fonts.googleapis.com/css?family=Roboto:300,400,700' rel='stylesheet' type='text/css'> -->
	<!-- Themify Icons -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl('template/css/themify-icons.css'); ?>">
	<!-- Bootstrap -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl('template/css/bootstrap.css') ?>">
	<!-- Owl Carousel -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl('template/css/owl.carousel.min.css') ?>">
	<link rel="stylesheet" href="<?php echo $this->baseUrl('template/css/owl.theme.default.min.css')?>">
	<!-- Magnific Popup -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl('template/css/magnific-popup.css')?>">
	<!-- Superfish -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl('template/css/superfish.css')?>">
	<!-- Easy Responsive Tabs -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl('template/css/easy-responsive-tabs.css') ?>">
	<!-- Animate.css -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl('template/css/animate.css') ?>">
	<!-- Theme Style -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl('template/css/style.css') ?>">
    <!-- css ui -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('client/lib-css/jquery-ui.css') ?>">
    <!-- Css W3 -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl('template/css/w3.css') ?>">
    <!-- Css font-awesome.min -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl('template/css/font-awesome.min.css') ?>">
    <!-- js for page -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl() .'/client/'.strtolower($_SESSION["paramUrl"]["module"]).'/'.strtolower($_SESSION["paramUrl"]["controller"]).'/'.strtolower($_SESSION["paramUrl"]["action"]).'/style.css' ?>">
    <!-- link-icon-awesome -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('client/lib-css/fontawesome-all.min.css') ?>">
    
    <!-- set base url js-->
    <script type="text/javascript">
    	var ROOT_URL = "<?php echo $this->baseUrl(); ?>" + "/index.php";
    </script>
	<!-- Modernizr JS -->
	<script src="<?php echo $this->baseUrl('template/js/modernizr-2.6.2.min.js') ?>"></script>
        <link rel="stylesheet" href="<?php echo $this->baseUrl('client/css/style.css') ?>">
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->
    
	</head>
	<body>
		<!-- START #fh5co-header -->
		<header id="fh5co-header-section" role="header" class="" >
			<?php  echo $this->render('header.phtml');?>
		</header>

		<div id="fh5co-main">
			<?php echo $this->layout()->content; ?>
		</div>
		<!-- END fhtco-main -->

                <div id="box-popup" class="modal">
                    
                 </div>
		<footer role="contentinfo" id="fh5co-footer">
			<?php echo $this->render('footer.phtml'); ?>
		</footer>
			
			
		<!-- jQuery -->
		<script src="<?php echo $this->baseUrl('template/js/jquery-1.10.2.min.js')?>"></script>
        <!--jquery form-->
        <script src="<?php echo $this->baseUrl('client/lib-js/jquery.form.js')?>"></script>

        <!-- jquery-ui -->
        <script src="<?php echo $this->baseUrl('client/lib-js/jquery-ui.min.js')?>"></script>
		<!-- jQuery Easing -->
		<script src="<?php echo $this->baseUrl('template/js/jquery.easing.1.3.js')?>"></script>
		<!-- Bootstrap -->
		<script src="<?php echo $this->baseUrl('template/js/bootstrap.js')?>"></script>
		<!-- Owl carousel -->
		<script src="<?php echo $this->baseUrl('template/js/owl.carousel.min.js')?>"></script>
		<!-- Magnific Popup -->
		<script src="<?php echo $this->baseUrl('template/js/jquery.magnific-popup.min.js')?>"></script>
		<!-- Superfish -->
		<script src="<?php echo $this->baseUrl('template/js/hoverIntent.js')?>"></script>
		<script src="<?php echo $this->baseUrl('template/js/superfish.js')?>"></script>
		<!-- Easy Responsive Tabs -->
		<script src="<?php echo $this->baseUrl('template/js/easyResponsiveTabs.js')?>"></script>
		<!-- FastClick for Mobile/Tablets -->
		<script src="<?php echo $this->baseUrl('template/js/fastclick.js')?>"></script>
		<!-- Waypoints -->
		<script src="<?php echo $this->baseUrl('template/js/jquery.waypoints.min.js')?>"></script>
		<!-- Main JS -->
		<script src="<?php echo $this->baseUrl('template/js/main.js')?>"></script>
        <script src="<?php echo $this->baseUrl('client/js/js.js') ?>"></script>
        <!-- js for page -->
        <script src="<?php echo $this->baseUrl() .'/client/'.strtolower($_SESSION["paramUrl"]["module"]).'/'.strtolower($_SESSION["paramUrl"]["controller"]).'/'.strtolower($_SESSION["paramUrl"]["action"]).'/js.js' ?>"></script>
        <script>
            // Get the modal
            var modal = document.getElementById('box-popup');

            // When the user clicks anywhere outside of the modal, close it
            window.onclick = function(event) {
                if (event.target == modal) {
                    Default.closePopup();
                }
            }
        </script>
	</body>
</html>

