<?php foreach ($this->aryListComment as $comment) { ?>
    <div style="margin-top:10px;">
        <div class="fleft fleft w3-text-grey w3-card-4" style=" width: 20%">
            <a href="<?php echo $this->baseUrl("User/index/userCode/".$comment['comment_user_code']); ?>">
                <img src="<?php foreach ($this->aryUser as $user) {
                echo ($comment['comment_user_code'] == $user['user_code'])? $this->baseUrl($user["user_url_image_alias"]) : $this->baseUrl('/client/image/user/avatarDefault.jpeg');
            }  ?>" class="w100p">
                </a>
        </div>
        <div class="fleft fleft w3-text-grey w3-card-4" style=" width: 80%; padding-left: 5px;">
            <h3 style="color:red"><?php foreach ($this->aryUser as $user) {
                echo ($comment['comment_user_code'] == $user['user_code'])? $user["user_full_name"] : "";
            }  ?></h3>
            <span style="max-width: 80%; font-size: 18px; font-weight: 800"><?php echo $comment['comment_content'] ?></span>  
            <br><span style="width:20%"><?php echo $comment['created']; ?></span>
        </div>
    </div>
<?php } ?>