                <?php foreach ($this->aryListVideo as $aryVideo) { ?>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <a class="fh5co-card" href="<?php echo $this->baseUrl("Video/view/id/".$aryVideo['id']); ?>">
                            <img class="itemAliasVideo" src="<?php echo $this->baseUrl($aryVideo['video_url_image_alias']);?>" alt="Free HTML5 Bootstrap template" class="img-responsive">
                            <div class="fh5co-card-body">
                                <h3><?php echo $aryVideo['video_title'];?></h3>
                                <p><?php echo $aryVideo['video_description'];?></p>
                            </div>
                        </a>
                    </div>
                <?php } ?>
        <!-- End Right Column -->
        <nav aria-label="Page navigation example" style="width: 100%">
            <ul class="pagination">
              <li class="page-item">
                <?php if($this->hasFirst) : ?>
                    <a class="page-link" href="#" aria-label="Previous1" onclick="User.loadPagination('Video','loadlistvideo','<?php echo $this->firstPage ?>','list_video')">
                        <span aria-hidden="true"> << </span>
                        <span class="sr-only">Previous1</span>
                    </a>
                <?php else : ?>
                <?php endif; ?>
              </li>
              <li class="page-item">
                <?php if ($this->hasPrev) : ?>
                    <!-- <a href="">First</a> -->
                    <a class="page-link" href="#" aria-label="Previous2" onclick="User.loadPagination('Video','loadlistvideo','<?php echo $this->previousPage ?>','list_video')">
                    <span aria-hidden="true"> < </span>
                    <span class="sr-only">Previous2</span>
                </a>
                <?php else : ?>
                <?php endif; ?> 
              </li>
              <?php if ($this->countPages != $this->currentPage) : ?>
              <li class="page-item"><a class="page-link" href="#"><?php echo "".$this->currentPage."/".$this->countPages; ?></a></li>
              <?php endif; ?>
              <li class="page-item">
                  <?php if ($this->hasNext) : ?>
                    <a class="page-link" href="#" aria-label="Next1" href="#" onclick="User.loadPagination('Video','loadlistvideo','<?php echo $this->nextPage ?>','list_video')"> 
                        <span aria-hidden="true"> > </span>
                        <span class="sr-only">Next1</span>
                    </a>
                  <?php else : ?>
                  <?php endif; ?>
              </li>
              <li class="page-item">
                  <?php if($this->hasEnd) : ?>
                    <a class="page-link" href="#" aria-label="Next" onclick="User.loadPagination('Video','loadlistvideo','<?php echo $this->endPage ?>','list_video')"> 
                        <span aria-hidden="true"> >> </span>
                        <span class="sr-only">Next</span>
                    </a>
              </li>
                  <?php else : ?>
                  <?php endif; ?> 
            </ul>
        </nav>