<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
div#video_player_box{ width:50%; background:#000; margin:0px auto;margin-top: 72px;}
div#video_controls_bar{ background: #333; padding:10px; color:#CCC; font-family:"Trebuchet MS", Arial, Helvetica, sans-serif;}
button#playpausebtn{
	background:url("<?php echo $this->baseUrl('/template/images/pause.png'); ?>");
        background-size: 100% 100%;
	border:none;
	width:16px;
	height:18px;
	cursor:pointer;
	opacity:0.5;
}
button#playpausebtn:hover{ opacity:1; }
input#seekslider{ width:63%; }
input#volumeslider{ width: 80px;}
input[type='range'] {
    -webkit-appearance: none !important;
    background: #000;
	border:#666 1px solid;
    height:4px;
}
input[type='range']::-webkit-slider-thumb {
    -webkit-appearance: none !important;
    background: #FFF;
    height:15px;
    width:15px;
	border-radius:100%;
	cursor:pointer;
}
</style>
<script>
var vid, playbtn, seekslider, curtimetext, durtimetext, mutebtn, volumeslider, fullscreenbtn;
function intializePlayer(){
	// Set object references
	vid = document.getElementById("my_video");
	playbtn = document.getElementById("playpausebtn");
	seekslider = document.getElementById("seekslider");
	curtimetext = document.getElementById("curtimetext");
	durtimetext = document.getElementById("durtimetext");
	mutebtn = document.getElementById("mutebtn");
	volumeslider = document.getElementById("volumeslider");
	fullscreenbtn = document.getElementById("fullscreenbtn");
	// Add event listeners
	playbtn.addEventListener("click",playPause,false);
	seekslider.addEventListener("change",vidSeek,false);
	vid.addEventListener("timeupdate",seektimeupdate,false);
	mutebtn.addEventListener("click",vidmute,false);
	volumeslider.addEventListener("change",setvolume,false);
	fullscreenbtn.addEventListener("click",toggleFullScreen,false);
}
window.onload = intializePlayer;
function playPause(){
	if(vid.paused){
		vid.play();
		playbtn.style.background = "url(<?php echo $this->baseUrl('/template/images/pause.png'); ?>)";
                playbtn.style.backgroundSize = "100% 100%";
	} else {
		vid.pause();
		playbtn.style.background = "url(<?php echo $this->baseUrl('/template/images/play.png'); ?>)";
                playbtn.style.backgroundSize = "100% 100%";
	}
}
function vidSeek(){
	var seekto = vid.duration * (seekslider.value / 100);
	vid.currentTime = seekto;
}
function seektimeupdate(){
	var nt = vid.currentTime * (100 / vid.duration);
	seekslider.value = nt;
	var curmins = Math.floor(vid.currentTime / 60);
	var cursecs = Math.floor(vid.currentTime - curmins * 60);
	var durmins = Math.floor(vid.duration / 60);
	var dursecs = Math.floor(vid.duration - durmins * 60);
	if(cursecs < 10){ cursecs = "0"+cursecs; }
	if(dursecs < 10){ dursecs = "0"+dursecs; }
	if(curmins < 10){ curmins = "0"+curmins; }
	if(durmins < 10){ durmins = "0"+durmins; }
	curtimetext.innerHTML = curmins+":"+cursecs;
	durtimetext.innerHTML = durmins+":"+dursecs;
}
function vidmute(){
	if(vid.muted){
		vid.muted = false;
		mutebtn.style.background = "url(<?php echo $this->baseUrl('/template/images/mute.png'); ?>)";
                mutebtn.style.backgroundSize = "100% 100%";
	} else {
		vid.muted = true;
		mutebtn.style.background = "url(<?php echo $this->baseUrl('/template/images/unmute.png'); ?>)";
                mutebtn.style.backgroundSize = "100% 100%";
	}
}
function setvolume(){
	vid.volume = volumeslider.value / 100;
}
function toggleFullScreen(){
	if(vid.requestFullScreen){
		vid.requestFullScreen();
	} else if(vid.webkitRequestFullScreen){
		vid.webkitRequestFullScreen();
	} else if(vid.mozRequestFullScreen){
		vid.mozRequestFullScreen();
	}
}
</script>
</head>
<div class="w25p fleft" id="box_comment" style="margin-top:72px; height: 569px; border: thin solid">
    <div id="list_comment" class="w100p" style="height:485px; overflow-y: auto; border-bottom: thin solid">
        <?php foreach ($this->aryListComment as $comment) { ?>
            <div>
                <div style=" margin-left: 3px">
                    <span style="width:80%; font-size: 18px; font-weight: 800"><?php echo $comment['comment_content'] ?></span>  
                    <br><span style="width:20%"><?php echo $comment['created']; ?></span>
                    <br><font><?php foreach ($this->aryUser as $user) {
                        echo ($comment['comment_user_code'] == $user['user_code'])? $user["user_full_name"] : "";
                    }  ?></font>
                </div>
            </div>
        <?php } ?>
    </div>
    <div id="insert_comment" class="w100p" style="height:70px; margin-top: 5px">
        <?php if ($this->isLogin == 1) :?>
        <textarea class="w98p" id="box_comment"></textarea>
        <?php endif; ?>
    </div>
</div>
<div id="video_player_box" style="margin-top:72px" class="fleft">
  <video id="my_video" width="100%" height="500" autoplay>
    <source src="<?php echo $this->baseUrl($this->aryVideo['video_url_video']); ?>">
  </video>
    <input type="hidden" id="video_code_hidden" value="<?php echo $this->aryVideo['video_code']; ?>" >
  <div id="video_controls_bar">
      <button id="playpausebtn" style="display:inline-block"></button>
    <input style="display:inline-block" id="seekslider" type="range" min="0" max="100" value="0" step="1">
    <span style="display:inline-block;" id="curtimetext">00:00</span> / <span id="durtimetext">00:00</span>
    <button style="display:inline-block; background: url('/watchDailyTV/public/template/images/mute.png') 0% 0% / 100% 100%;" id="mutebtn" ></button>
    <input style="display:inline-block" id="volumeslider" type="range" min="0" max="100" value="100" step="1">
    <button style="display:inline-block; background: url('/watchDailyTV/public/template/images/fullscreen.jpeg') 0% 0% / 100% 100%;" id="fullscreenbtn"></button>
  </div>
</div>
<div class="w24p fleft" id="box_video_like" style="margin-top:72px; height: 566px; overflow-y: auto; border: thin solid">
    <table class=" w100p">
        <colgroup>
            <col style="width:30%"/>
            <col style="width:70%"/>
        </colgroup>
        <?php if (isset($this->aryListVideoLike) && $this->aryListVideoLike != null) {
            foreach ($this->aryListVideoLike as $key => $video) { ?>
        <tr style=" background-color: #CCC">
                    <td><a href="<?php echo $this->baseUrl("Video/view/id/".$video['id']); ?>">
                        <img src="<?php echo $this->baseUrl($video['video_url_image_alias']);?>" class="w100p">
                        </a>
                    </td>
                    <td>
                        <div style="margin-top:0px"  class="w100p">
                            <h4 style="word-wrap:  break-word;width: 300px"><?php echo (strlen($video['video_title']) > 50)? substr($video['video_title'],0,50)."..." : $video['video_title'];?></h4>
                            <h5 style=" color: #666"><?php 
                              foreach ($this->aryUser as $user) {
                                  echo ($user['user_code'] == $video['video_type_account']) ? $user['user_full_name'] : "";
                              }
                            ?></h5>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <br>
                    </td>
                </tr>
        <?php }}  ?>
    </table>
    <div class="w100p" style="margin-left:5px">
        
        <span></span>
    </div>
</div>
<div class="" style="width: 90%; box-sizing: border-box; margin: 700px 5% 5px 5%; background: #CCC; border: thin solid">
    <div>
        <h2 style=" margin-left: 20px"><?php echo $this->aryVideo['video_title'] ?></h2>
        <div style=" margin-left: 40px">
            <font style=" font-size: 25px"><?php echo $this->aryVideo['video_view'] ?> views</font>
            <a>
                <i id="iconTotalDisLike" onclick="Video.likeVideo(<?php echo $this->aryVideo['id'] ?>, 0,this)" class="fa fa-thumbs-down <?php echo ($this->aryLike['like_is_like'] == 0 && $this->aryLike['like_is_choose'] == 1) ? 'w3-text-blue' : 'w3-text-white' ?>" style="font-size: 35px; float: right;">
                    &nbsp;<font style=" color: black" id="totalDisLike"><?php echo $this->totalDisLike; ?></font>
                </i>
            </a>
           
            <a>
                <i id="iconTotalLike" onclick="Video.likeVideo(<?php echo $this->aryVideo['id'] ?>, 1,this)" class="fa fa-thumbs-up <?php echo ($this->aryLike['like_is_like'] == 1 && $this->aryLike['like_is_choose'] == 1) ? 'w3-text-blue' : 'w3-text-white' ?>" style="font-size: 35px; float: right; margin-right: 90px">
                    &nbsp;<font style=" color: black" id="totalLike"><?php echo $this->totalLike; ?></font>
                </i>
            </a>
        </div>
    </div>
    <hr>
    <div style=" border-top: thin solid black; overflow-y: auto; max-height: 400px">
        <h3 style="color: #002752">Desscription Video : </h3>
        <h4 style=" margin-left: 30px"><?php echo $this->aryVideo['video_description'] ?></h4>
    </div>
</div>
