<head>
<style>
div#video_player_box{ width:50%; background:#000; margin:0px auto;margin-top: 72px;}
div#video_controls_bar{ background: #333; padding:10px; color:#CCC; font-family:"Trebuchet MS", Arial, Helvetica, sans-serif;}
button#playpausebtn{
	background:url("<?php echo $this->baseUrl('/template/images/pause.png'); ?>");
        background-size: 100% 100%;
	border:none;
	width:16px;
	height:18px;
	cursor:pointer;
	opacity:0.5;
}
button#playpausebtn:hover{ opacity:1; }
input#seekslider{ width:65%; }
input#volumeslider{ width: 80px;}
input[type='range'] {
    -webkit-appearance: none !important;
    background: #000;
	border:#666 1px solid;
    height:4px;
}
input[type='range']::-webkit-slider-thumb {
    -webkit-appearance: none !important;
    background: #FFF;
    height:15px;
    width:15px;
	border-radius:100%;
	cursor:pointer;
}
</style>
<script>
var vid, playbtn, seekslider, curtimetext, durtimetext, mutebtn, volumeslider, fullscreenbtn;
function intializePlayer(){
	// Set object references
	vid = document.getElementById("my_video");
	playbtn = document.getElementById("playpausebtn");
	seekslider = document.getElementById("seekslider");
	curtimetext = document.getElementById("curtimetext");
	durtimetext = document.getElementById("durtimetext");
	mutebtn = document.getElementById("mutebtn");
	volumeslider = document.getElementById("volumeslider");
	fullscreenbtn = document.getElementById("fullscreenbtn");
	// Add event listeners
	playbtn.addEventListener("click",playPause,false);
	seekslider.addEventListener("change",vidSeek,false);
	vid.addEventListener("timeupdate",seektimeupdate,false);
	mutebtn.addEventListener("click",vidmute,false);
	volumeslider.addEventListener("change",setvolume,false);
	fullscreenbtn.addEventListener("click",toggleFullScreen,false);
}
window.onload = intializePlayer;
function playPause(){
	if(vid.paused){
		vid.play();
		playbtn.style.background = "url(<?php echo $this->baseUrl('/template/images/pause.png'); ?>)";
                playbtn.style.backgroundSize = "100% 100%";
	} else {
		vid.pause();
		playbtn.style.background = "url(<?php echo $this->baseUrl('/template/images/play.png'); ?>)";
                playbtn.style.backgroundSize = "100% 100%";
	}
}
function vidSeek(){
	var seekto = vid.duration * (seekslider.value / 100);
	vid.currentTime = seekto;
}
function seektimeupdate(){
	var nt = vid.currentTime * (100 / vid.duration);
	seekslider.value = nt;
	var curmins = Math.floor(vid.currentTime / 60);
	var cursecs = Math.floor(vid.currentTime - curmins * 60);
	var durmins = Math.floor(vid.duration / 60);
	var dursecs = Math.floor(vid.duration - durmins * 60);
	if(cursecs < 10){ cursecs = "0"+cursecs; }
	if(dursecs < 10){ dursecs = "0"+dursecs; }
	if(curmins < 10){ curmins = "0"+curmins; }
	if(durmins < 10){ durmins = "0"+durmins; }
	curtimetext.innerHTML = curmins+":"+cursecs;
	durtimetext.innerHTML = durmins+":"+dursecs;
}
function vidmute(){
	if(vid.muted){
		vid.muted = false;
		mutebtn.style.background = "url(<?php echo $this->baseUrl('/template/images/mute.png'); ?>)";
                mutebtn.style.backgroundSize = "100% 100%";
	} else {
		vid.muted = true;
		mutebtn.style.background = "url(<?php echo $this->baseUrl('/template/images/unmute.png'); ?>)";
                mutebtn.style.backgroundSize = "100% 100%";
	}
}
function setvolume(){
	vid.volume = volumeslider.value / 100;
}
function toggleFullScreen(){
	if(vid.requestFullScreen){
		vid.requestFullScreen();
	} else if(vid.webkitRequestFullScreen){
		vid.webkitRequestFullScreen();
	} else if(vid.mozRequestFullScreen){
		vid.mozRequestFullScreen();
	}
}
</script>
</head>
<div class="w25p fleft" id="box_comment" style="margin-top:72px; height: 569px">
    <div id="list_comment" class="w100p" style="height:466px"></div>
    <div id="insert_comment" class="w100p" style="height:70px">
        <textarea class="w98p" id="box_comment"></textarea>
        <input type="button" value="Send Comment" id="btnSendComment" >
    </div>
</div>
<div id="video_player_box" style="margin-top:72px" class="fleft">
  <video id="my_video" width="100%" height="500" autoplay>
    <source src="<?php echo $this->baseUrl($this->aryVideo['video_url_video']); ?>">
  </video>
    <input type="hidden" id="video_code_hidden" value="<?php echo $this->aryVideo['video_code']; ?>" >
  <div id="video_controls_bar">
      <button id="playpausebtn" style="display:inline-block"></button>
    <input style="display:inline-block" id="seekslider" type="range" min="0" max="100" value="0" step="1">
    <span style="display:inline-block;" id="curtimetext">00:00</span> / <span id="durtimetext">00:00</span>
    <button style="display:inline-block; background: url('/watchDailyTV/public/template/images/mute.png') 0% 0% / 100% 100%;" id="mutebtn" ></button>
    <input style="display:inline-block" id="volumeslider" type="range" min="0" max="100" value="100" step="1">
    <button style="display:inline-block; background: url('/watchDailyTV/public/template/images/fullscreen.jpeg') 0% 0% / 100% 100%;" id="fullscreenbtn"></button>
  </div>
</div>
<div class="w24p fleft" id="box_video_like" style="margin-top:72px; height: 466px">dfghdfghfdh</div>
