<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
</style>
<div class="w3-light-grey mar-top-75">
<div class="w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
  
    <!-- Left Column -->
    <div class="w3-third">
    
      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-display-container">
          <img src="<?php echo $this->baseUrl('/client/image/user/avatarDefault.jpeg') ?>" style="width:100%; height:350px" alt="Avatar">
          <div class="w3-display-bottomleft w3-container w3-text-black">
            <h2><?php echo $this->aryUser['user_full_name'] ?></h2>
          </div>
        </div>
        <div class="w3-container">
          <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i><?php echo $this->aryUser['user_jog_present'] ?></p>
          <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i><?php echo $this->arrStreet['street_name']."-".$this->arrDistrict['district_name']."-".$this->arrCity['city_name'] ?></p>
          <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i><?php echo $this->aryUser['user_email'] ?></p>
          <p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-teal"></i><?php echo $this->aryUser['user_phone'] ?></p>
          <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-large w3-text-teal"></i><?php echo $this->aryUser['user_birthday'] ?></p>
          <div style="width: 100%"><a href="#" class="mar-left-94p" onclick="UserInfo.showPopupEditUserInfo(1)"><i class="fa fa-edit w3-margin-right w3-large w3-text-red"></i></a></div>
        </div>
      </div><br>

    <!-- End Left Column -->
    </div>

    <!-- Right Column -->
    <div class="w3-twothird">
    
        <div class="w3-container w3-card w3-white w3-margin-bottom">
            <h2 class="w3-text-grey w3-padding-16" onclick="Default.uploadVideo()"><i class="fa fa-upload fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i></h2>

            <div class="w3-container" id="boxContentVideo">

            </div>
        </div>

        <div class="w3-container w3-card w3-white">
            <div style=" height: 5px"></div>
            <div class="ui-widget ui-helper-clearfix" id="list_video">
                <?php foreach ($this->aryListVideo as $aryVideo) { ?>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <a class="fh5co-card" href="<?php echo $this->baseUrl("Video/view/id/".$aryVideo['id']); ?>">
                            <img style="width:300px; height:180px" src="<?php echo $this->baseUrl($aryVideo['video_url_image_alias']);?>" alt="Free HTML5 Bootstrap template" class="img-responsive">
                            <div class="fh5co-card-body">
                                <h3><?php echo $aryVideo['video_title'];?></h3>
                                <p><?php echo $aryVideo['video_description'];?></p>
                            </div>
                        </a>
                    </div>
                <?php } ?>
                 <nav aria-label="Page navigation example">
                <ul class="pagination">
                  <li class="page-item">
                    <?php if($this->hasFirst) : ?>
                        <a class="page-link" href="#" aria-label="Previous1" onclick="User.loadPagination('Video','loadlistvideo','<?php echo $this->firstPage ?>','list_video')">
                            <span aria-hidden="true"> << </span>
                            <span class="sr-only">Previous1</span>
                        </a>
                    <?php else : ?>
                    <?php endif; ?>
                  </li>
                  <li class="page-item">
                    <?php if ($this->hasPrev) : ?>
                        <!-- <a href="">First</a> -->
                        <a class="page-link" href="#" aria-label="Previous2" onclick="User.loadPagination('Video','loadlistvideo','<?php echo $this->previousPage ?>','list_video')">
                        <span aria-hidden="true"> < </span>
                        <span class="sr-only">Previous2</span>
                    </a>
                    <?php else : ?>
                    <?php endif; ?> 
                  </li>
                  <?php if ($this->countPages != $this->currentPage) : ?>
                  <li class="page-item"><a class="page-link" href="#"><?php echo "".$this->currentPage."/".$this->countPages; ?></a></li>
                  <?php endif; ?>
                  <li class="page-item">
                      <?php if ($this->hasNext) : ?>
                        <a class="page-link" href="#" aria-label="Next1" href="#" onclick="User.loadPagination('Video','loadlistvideo','<?php echo $this->nextPage ?>','list_video')"> 
                            <span aria-hidden="true"> > </span>
                            <span class="sr-only">Next1</span>
                        </a>
                      <?php else : ?>
                      <?php endif; ?>
                  </li>
                  <li class="page-item">
                      <?php if($this->hasEnd) : ?>
                        <a class="page-link" href="#" aria-label="Next" onclick="User.loadPagination('Video','loadlistvideo','<?php echo $this->endPage ?>','list_video')">
                            <span aria-hidden="true"> >> </span>
                            <span class="sr-only">Next</span>
                        </a>
                  </li>
                      <?php else : ?>
                      <?php endif; ?> 
                </ul>
            </nav>
            </div>
        <!-- End Right Column -->
        </div>
       
    <!-- End Grid -->
    </div>
  
  <!-- End Page Container -->
</div>
<div style="margin-top: 10px;float: right;">

      

</div>
</div>
<div style="width: 100%"><a href="#"><i class="fa fa-save w3-margin-right w3-large w3-text-red"></i></a></div>
<div style="width: 100%"><a href="#"><i class="fa fa-remove w3-margin-right w3-large w3-text-red"></i></a></div>
<div style="width: 100%"><a href="#"><i class="fa fa-create w3-margin-right w3-large w3-text-red"></i></a></div>
