<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
</style>
<div class="w3-light-grey mar-top-75">
<div class="w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
  
    <!-- Left Column -->
    <div class="w3-third">
    
      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-display-container">
          <img src="<?php echo $this->baseUrl('/client/image/user/avatarDefault.jpeg') ?>" style="width:100%; height:350px" alt="Avatar">
          <div class="w3-display-bottomleft w3-container w3-text-black">
            <h2><?php echo $this->aryUser['user_full_name'] ?></h2>
          </div>
        </div>
        <div class="w3-container">
          <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i><?php echo $this->aryUser['user_jog_present'] ?></p>
          <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i><?php echo $this->arrStreet['street_name']."-".$this->arrDistrict['district_name']."-".$this->arrCity['city_name'] ?></p>
          <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i><?php echo $this->aryUser['user_email'] ?></p>
          <p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-teal"></i><?php echo $this->aryUser['user_phone'] ?></p>
          <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-large w3-text-teal"></i><?php echo $this->aryUser['user_birthday'] ?></p>
          <div style="width: 100%"><a href="#" class="mar-left-94p" onclick="UserInfo.showPopupEditUserInfo(1)"><i class="fa fa-edit w3-margin-right w3-large w3-text-red"></i></a></div>
          <hr>
          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Account</b></p>
          <p></p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:90%">90%</div>
          </div>
          <p>Photography</p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:80%">
              <div class="w3-center w3-text-white">80%</div>
            </div>
          </div>
          <p>Illustrator</p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:75%">75%</div>
          </div>
          <p>Media</p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:50%">50%</div>
          </div>
          <br>

          <p class="w3-large w3-text-theme"><b><i class="fa fa-globe fa-fw w3-margin-right w3-text-teal"></i>Languages</b></p>
          <p>English</p>
          <div class="w3-light-grey w3-round-xlarge">
            <div class="w3-round-xlarge w3-teal" style="height:24px;width:100%"></div>
          </div>
          <p>Spanish</p>
          <div class="w3-light-grey w3-round-xlarge">
            <div class="w3-round-xlarge w3-teal" style="height:24px;width:55%"></div>
          </div>
          <p>German</p>
          <div class="w3-light-grey w3-round-xlarge">
            <div class="w3-round-xlarge w3-teal" style="height:24px;width:25%"></div>
          </div>
          <br>
        </div>
      </div><br>

    <!-- End Left Column -->
    </div>

    <!-- Right Column -->
    <div class="w3-twothird">
    
      <div class="w3-container w3-card w3-white w3-margin-bottom">
        <h2 class="w3-text-grey w3-padding-16" onclick="Default.uploadVideo()"><i class="fa fa-upload fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i></h2>
        
        <div class="w3-container" id="boxContentVideo">
          <form>
            <table style="width: 100%">
              <tr>
                <td colspan="2">
                  <div class="imgcontainer">
                    <video width="320" height="260" id="video" src="" controls>
                      Your browser does not support the video tag.
                    </video>
                  </div>
                  <input type="file" name="video[video_url_video]" onchange="User.loadVideo(this)" style="margin: 0px 0px 0px 5px">
                </td>
              </tr>
              <tr>
                <td>
                  <label for="videoname">Video Name</label>
                  <input type="text" name="video[video_title]" id="videotitle" maxlength="100">
                </td>
                <td>
                  <label for="videodescription">Video Name</label>
                  <textarea name="video[video_description]" id="videodescription" maxlength="1000">
                  </textarea>
                </td>
              </tr>
              <tr>
                <td>
                  <label >Video Type</label>
                  <select>
                    <option>1</option>
                    <option>2</option>
                  </select>
                </td>
                <td>
                  <label for="">Video Image Alias</label><img src="" id="imgAlias" style="width: 50px ; height: 50px">
                  <input type="file" name="video[video_url_images_alias]" onchange="User.loadImg(this,'imgAlias')" style="margin: 0px 0px 0px 5px">
                  </textarea>
                </td>
              </tr>
            </table>
          </form>
        </div>
      </div>

      <div class="w3-container w3-card w3-white" style="height:539px">
	  <div class="ui-widget ui-helper-clearfix">
	  
	 <ul id="gallery" class="gallery ui-helper-reset ui-helper-clearfix" style="overflow-y:auto; height:500px">
	   <li class="ui-widget-content ui-corner-tr">
		 <h5 class="ui-widget-header">High Tatras</h5>
		 <img src="images/high_tatras_min.jpg" alt="The peaks of High Tatras" width="96" height="72">
		 <a href="images/high_tatras.jpg" title="View larger image" class="ui-icon ui-icon-zoomin">View larger</a>
		 <a href="link/to/trash/script/when/we/have/js/off" title="Delete this image" class="ui-icon ui-icon-trash">Delete image</a>
	   </li>
	   <li class="ui-widget-content ui-corner-tr">
		 <h5 class="ui-widget-header">High Tatras 2</h5>
		 <img src="images/high_tatras2_min.jpg" alt="The chalet at the Green mountain lake" width="96" height="72">
		 <a href="images/high_tatras2.jpg" title="View larger image" class="ui-icon ui-icon-zoomin">View larger</a>
		 <a href="link/to/trash/script/when/we/have/js/off" title="Delete this image" class="ui-icon ui-icon-trash">Delete image</a>
	   </li>
	   <li class="ui-widget-content ui-corner-tr">
		 <h5 class="ui-widget-header">High Tatras 3</h5>
		 <img src="images/high_tatras3_min.jpg" alt="Planning the ascent" width="96" height="72">
		 <a href="images/high_tatras3.jpg" title="View larger image" class="ui-icon ui-icon-zoomin">View larger</a>
		 <a href="link/to/trash/script/when/we/have/js/off" title="Delete this image" class="ui-icon ui-icon-trash">Delete image</a>
	   </li>
	   <li class="ui-widget-content ui-corner-tr">
		 <h5 class="ui-widget-header">High Tatras 4</h5>
		 <img src="images/high_tatras4_min.jpg" alt="On top of Kozi kopka" width="96" height="72">
		 <a href="images/high_tatras4.jpg" title="View larger image" class="ui-icon ui-icon-zoomin">View larger</a>
		 <a href="link/to/trash/script/when/we/have/js/off" title="Delete this image" class="ui-icon ui-icon-trash">Delete image</a>
	   </li>
	   <li class="ui-widget-content ui-corner-tr">
		 <h5 class="ui-widget-header">High Tatras</h5>
		 <img src="images/high_tatras_min.jpg" alt="The peaks of High Tatras" width="96" height="72">
		 <a href="images/high_tatras.jpg" title="View larger image" class="ui-icon ui-icon-zoomin">View larger</a>
		 <a href="link/to/trash/script/when/we/have/js/off" title="Delete this image" class="ui-icon ui-icon-trash">Delete image</a>
	   </li>
	   <li class="ui-widget-content ui-corner-tr">
		 <h5 class="ui-widget-header">High Tatras 2</h5>
		 <img src="images/high_tatras2_min.jpg" alt="The chalet at the Green mountain lake" width="96" height="72">
		 <a href="images/high_tatras2.jpg" title="View larger image" class="ui-icon ui-icon-zoomin">View larger</a>
		 <a href="link/to/trash/script/when/we/have/js/off" title="Delete this image" class="ui-icon ui-icon-trash">Delete image</a>
	   </li>
	   <li class="ui-widget-content ui-corner-tr">
		 <h5 class="ui-widget-header">High Tatras 3</h5>
		 <img src="images/high_tatras3_min.jpg" alt="Planning the ascent" width="96" height="72">
		 <a href="images/high_tatras3.jpg" title="View larger image" class="ui-icon ui-icon-zoomin">View larger</a>
		 <a href="link/to/trash/script/when/we/have/js/off" title="Delete this image" class="ui-icon ui-icon-trash">Delete image</a>
	   </li>
	   <li class="ui-widget-content ui-corner-tr">
		 <h5 class="ui-widget-header">High Tatras 4</h5>
		 <img src="images/high_tatras4_min.jpg" alt="On top of Kozi kopka" width="96" height="72">
		 <a href="images/high_tatras4.jpg" title="View larger image" class="ui-icon ui-icon-zoomin">View larger</a>
		 <a href="link/to/trash/script/when/we/have/js/off" title="Delete this image" class="ui-icon ui-icon-trash">Delete image</a>
	   </li>
	   
	 </ul>
	  
	 <div id="trash" class="ui-widget-content ui-state-default">
	   <h4 class="ui-widget-header"><span class="ui-icon ui-icon-trash">Trash</span> Trash</h4>
	 </div>
	  
	 </div>
      </div>

    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
  <!-- End Page Container -->
</div>

</div>
<div style="width: 100%"><a href="#"><i class="fa fa-save w3-margin-right w3-large w3-text-red"></i></a></div>
<div style="width: 100%"><a href="#"><i class="fa fa-remove w3-margin-right w3-large w3-text-red"></i></a></div>
<div style="width: 100%"><a href="#"><i class="fa fa-create w3-margin-right w3-large w3-text-red"></i></a></div>
