<form id="formLogin" class="modal-content animate">
  <div class="imgcontainer">
    <span onclick="Default.closePopup('formLogin')" class="close" title="Close Modal">&times;</span>
    <img src="<?php echo $this->baseUrl('/client/image/user/avatarDefault.jpeg') ?>" alt="Avatar" class="avatar">
  </div>

  <div class="container-model">
    <label><b>Username</b></label>
    <input type="text" class="input100p" placeholder="Enter Username" name="user[user_login_name]" required>

    <label><b>Password</b></label>
    <input type="password" class="input100p" placeholder="Enter Password" name="user[user_login_pass]" required>

    <button type="submit" onclick="User.checkLoginAction()">Login</button>
    <input type="checkbox" checked="checked"> Remember me
    <div><a href="#" onclick="User.showPopupRegister()">Register?</a></div>
  </div>
  <div id="list_message_error">
    
  </div>
  <div class="container-model" style="background-color:#f1f1f1">
    <button type="submit" onclick="Default.closePopup('formLogin')" class="cancelbtn">Cancel</button>
    <span class="psw">Forgot <a href="#" onclick="User.showForgotPassword()">password?</a></span>
  </div>
</form>
