<form id="formForgotPassword" class="modal-content animate">
  <div class="imgcontainer">
    <span onclick="Default.closePopup('formLogin')" class="close" title="Close Modal">&times;</span>
  </div>

  <div class="container-model">
    <label><b>Username</b></label>
    <input type="text" class="input100p" placeholder="Enter Username" name="user_login_name" required>

    <label><b>Email</b></label>
    <input type="text" class="input100p" placeholder="Enter Email" name="user_email" required>

    <button type="submit" onclick="User.sendMailForgotPassword()" id="btnForgotPassword">Send Mail Confirm</button>
    <div><a href="#" onclick="User.showPopupRegister()">Register?</a></div>
  </div>
  <div id="list_message_error">
    
  </div>
  <div class="container-model" style="background-color:#f1f1f1">
    <button type="submit" onclick="Default.closePopup('formForgotPassword')" class="cancelbtn">Cancel</button>
    <span class="psw">Forgot <a href="#" onclick="User.showForgotPassword()">password?</a></span>
  </div>
</form>
