
<form id="formRegister" class="modal-content-register animate" enctype="multipart/form-data">
  <div class="imgcontainer">
  	<img src="<?php echo $this->baseUrl('/client/image/user/avatarDefault.jpeg') ?>" alt="Avatar" style="height: 105px" class="avatar" id="avatarUser">
    <span onclick="Default.closePopup('formLogin')" class="close" title="Close Modal">&times;</span>
    <input style="margin-left: 44%" type="file" id="inputAvatarUpload" name="avatarUser" onchange="User.loadImg(this)">
  </div>
  <div class="container-model-50p fleft">
    <label><b>First Name</b><font style="color: red"> *</font></label>
    <input type="text" class="input100p"
	    name="user[user_first_name]" 
	    id="user_first_name" value="<?php echo isset($_COOKIE['user_first_name']) ? $_COOKIE['user_first_name'] : ""; ?>" 
	    required
	>

    <label><b>Last Name</b><font style="color: red"> *</font></label>
    <input type="text" class="input100p"
	    name="user[user_last_name]" value="<?php echo isset($_COOKIE['user_last_name']) ? $_COOKIE['user_last_name'] : ""; ?>"
	    id="user_last_name" 
	    required
	>

    <label><b>Username</b><font style="color: red"> *</font></label>
    <input type="text" class="input100p"
	    name="user[user_login_name]" 
	    id="user_login_name" value="<?php echo isset($_COOKIE['user_login_name']) ? $_COOKIE['user_login_name'] : ""; ?>"
	    required
	>

  </div>
  <div class="container-model-50p fleft">
    <label><b>Email</b><font style="color: red"> *</font></label>
    <input type="text"  class="input100p"
	    name="user[user_email]" 
	    id="user_email" value="<?php echo isset($_COOKIE['user_email']) ? $_COOKIE['user_email'] : ""; ?>"
	    required
    >

    <label><b>Confirm Password</b><font style="color: red"> *</font></label>
    <input type="password" class="input100p"
	    name="user[user_login_pass]" 
	    id="user_login_pass" value="<?php echo isset($_COOKIE['user_login_pass']) ? $_COOKIE['user_login_pass'] : ""; ?>"
	    required
    >
    
    <label><b>Password</b><font style="color: red"> *</font></label>
    <input type="password" class="input100p"
	    name="user_login_pass_confirm" 
	    id="user_login_pass_confirm" value="<?php echo isset($_COOKIE['user_login_pass_confirm']) ? $_COOKIE['user_login_pass_confirm'] : ""; ?>"
	    required
    >
    <label><b>Birthday</b><font style="color: red"> *</font></label><br>
    <label><b>Year : </b></label> 
    <select class="select23p" name="user[birth-year]" id="date-year" onchange="Default.setDateTimeByYear(this)">
      <?php for ($i = 1900; $i <= 2050; $i++) { ?>
        <option value="<?php echo $i ?>" <?php if ($i == 1995) {echo "selected";} ?> >
          <?php echo $i ?>
        </option>
      <?php } ?>
    </select>
	  <label><b>Month : </b></label>
    <select class="select23p" name="user[birth-month]" id="date-month" onchange="Default.setDateTimeByMonth(this)">
      <?php for ($i = 1; $i <= 12; $i++) { ?>
        <option value="<?php echo $i ?>">
          <?php echo $i ?>
        </option>
      <?php } ?>
    </select>
	  <label><b>Date : </b></label> 
    <select class="select23p" name="user[birth-day]" id="date-day">
      <?php for ($i = 1; $i <= 31; $i++) { ?>
        <option value="<?php echo $i ?>">
          <?php echo $i ?>
        </option>
      <?php } ?>
    </select>
  </div>
  <div class="container-model" style="background-color:#f1f1f1">
    <button type="submit" onclick="User.checkRegisterAction()">Register</button>
    <input type="checkbox" checked="checked"> Remember me
    <img id="imgLoading" style="display: none; margin-left: 31%; width: 100px" src="<?php echo $this->baseUrl('/template/images/loading.gif') ?>">
  </div>
  <div id="list_message_error">
    
  </div>
  <div class="container-model" style="background-color:#f1f1f1">
    <button type="button" onclick="Default.closePopup('formLogin')" class="cancelbtn">Cancel</button>
    <span class="psw">Forgot <a href="#">password?</a></span>
  </div>
</form>
