<form id="formEdituser" class="modal-content-register animate" enctype="multipart/form-data">
    <div class="container-model-50p fleft" style="height: 400px">
    <label><b>First Name</b><font style="color: red"> *</font></label>
    <input type="text" class="input100p"
	    name="user[user_first_name]" 
	    id="user_first_name" value="<?php echo $this->arrCurrentUser['user_first_name']; ?>" 
	    required
	>

    <label><b>Last Name</b><font style="color: red"> *</font></label>
    <input type="text" class="input100p"
	    name="user[user_last_name]" value="<?php echo $this->arrCurrentUser['user_last_name']; ?>"
	    id="user_last_name" 
	    required
	>

    <label><b>Phone</b><font style="color: red"> *</font></label>
    <input type="text" class="input100p"
	    name="user[user_phone]" 
	    id="user_phone" value="<?php echo $this->arrCurrentUser['user_phone']; ?>"
	    required
	>
  <label><b>Birthday</b><font style="color: red"> *</font></label><br>
  <label><b>Year : </b></label> 
  <select class="select23p" name="user[birth-year]" id="date-year" onchange="Default.setDateTimeByYear(this)">
    <?php $date = $this->arrCurrentUser['user_birthday'];   
    $day = date("d", strtotime($date));
    $month = date("m", strtotime($date));
    $year = date("Y", strtotime($date));
    for ($i = 1900; $i <= 2050; $i++) { ?>
      <option value="<?php echo $i ?>" <?php if ($i == $year) {echo "selected";} ?> >
        <?php echo $i ?>
      </option>
    <?php } ?>
  </select>
  <label><b>Month : </b></label>
  <select class="select23p" name="user[birth-month]" id="date-month" onchange="Default.setDateTimeByMonth(this)">
    <?php for ($i = 1; $i <= 12; $i++) { ?>
      <option value="<?php echo $i ?>" <?php if ($i == $month) {echo "selected";} ?>>
        <?php echo $i ?>
      </option>
    <?php } ?>
  </select>
  <label><b>Date : </b></label> 
  <select class="select23p" name="user[birth-day]" id="date-day">
    <?php for ($i = 1; $i <= 31; $i++) { ?>
      <option value="<?php echo $i ?>" <?php if ($i == $day) {echo "selected";} ?>>
        <?php echo $i ?>
      </option>
    <?php } ?>
  </select>
  </div>
  <div class="container-model-50p fleft" style="height: 400px">
    <label><b>Email</b><font style="color: red"> *</font></label>
    <input type="text"  class="input100p"
	    name="user[user_email]" 
	    id="user_email" value="<?php echo $this->arrCurrentUser['user_email']; ?>"
	    required
    >

    <label><b>Job present</b><font style="color: red"> *</font></label>
    <input type="text" class="input100p"
	    name="user[user_jog_present]" 
	    id="user_jog_present" value="<?php echo $this->arrCurrentUser['user_jog_present']; ?>"
	    required
    >
    
    <label><b>Address</b><font style="color: red"> *</font></label><br>
    <label><b>City : </b></label> 
    <select class="select23p"  id="user_city" name="user[user_city]" onchange="Default.loadListSelected('user_city','user_district')"> 
      <?php foreach ($this->citys as $city) { ?>
          <option value="<?php echo $city['city_code'] ?>"><?php echo $city['city_name'] ?></option>
      <?php } ?>
    </select>
    <label class="display-none" id="lb_user_district"><b>District : </b></label>
    <select class="select23p display-none" id="user_district" name="user[user_district]" onchange="Default.loadListSelected('user_district','user_street');Default.setValueChangeSelect(this,'', 'user_district')">
    </select>
    <label class="display-none" id="lb_user_street"><b>Street : </b></label> 
    <select class="select23p display-none" id="user_street" name="user[user_street]" onchange="Default.setValueChangeSelect(this,'', 'user_street')">
      
    </select>
  </div>
  <div class="container-model" style="background-color:#f1f1f1">
    
  </div>
  <div id="list_message_error">
    
  </div>
  <div class="container-model" style="background-color:#f1f1f1; text-align: center">
    <button type="submit" onclick="User.saveUser()">Register</button>
    <img id="imgLoading" style="display: none; margin-left: 31%; width: 100px" src="<?php echo $this->baseUrl('/template/images/loading.gif') ?>">
    <button type="button" onclick="Default.closePopup('formLogin')" style="background-color: red; margin-left: 10px">Cancel</button>
  </div>
</form>
